networks:
  labnet:

services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    networks:
      - labnet
    volumes:
      - dind-storage:/var/lib/docker

  planter:
    image: docker:cli
    depends_on:
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2375
    networks:
      - labnet
    entrypoint: ["/bin/sh", "-c"]
    command:
      - "until docker info >/dev/null 2>&1; do sleep 1; done; docker run -d --name backdoor-c2 --label com.attacker.note=persistence alpine sleep 999999"

  app:
    build: ./app
    container_name: ccdc-25-container-escape-chain-app
    environment:
      DOCKER_HOST: tcp://dind:2375
    depends_on:
      - dind
    networks:
      - labnet
    ports:
      - "8202:5000"

volumes:
  dind-storage:
