# Challenge 07: Web App Config Hardening
# Difficulty: Medium
# Time estimate: 40-60 minutes
require 'rbconfig'

is_apple_silicon = RbConfig::CONFIG['host_os'] =~ /darwin/ && RbConfig::CONFIG['host_cpu'] =~ /arm|aarch64/

if is_apple_silicon
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "WidgetCorp-App"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "scripts/break_server.yml"
    ansible.become = true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["memsize"] = "1024"
    vmware.vmx["numvcpus"] = "1"
    vmware.allowlist_verified = true
  end
end
